// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/to404hanga/onlinue_judge_gateway/ioc"
	"github.com/to404hanga/onlinue_judge_gateway/service"
	"github.com/to404hanga/onlinue_judge_gateway/web"
)

// Injectors from wire.go:

func BuildDependency() *web.GinServer {
	logger := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	handler := ioc.InitJWTHandler(cmdable)
	db := ioc.InitDB()
	authService := service.NewAuthService(db)
	authHandler := web.NewAuthHandler(authService, handler, logger)
	proxyHandler := ioc.InitProxyHandler(logger)
	ginServer := ioc.InitGinServer(logger, handler, db, authHandler, proxyHandler)
	return ginServer
}
