// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/to404hanga/online_judge_gateway/ioc"
	"github.com/to404hanga/online_judge_gateway/service"
	"github.com/to404hanga/online_judge_gateway/web"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func BuildDependency() *web.GinServer {
	logger := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	handler := ioc.InitJWTHandler(cmdable)
	db := ioc.InitDB()
	cache := ioc.InitLRUCache()
	authService := service.NewAuthService(db, cmdable, logger, cache)
	authHandler := web.NewAuthHandler(authService, handler, logger)
	client := ioc.InitEtcdClient()
	proxyHandler := ioc.InitProxyHandler(logger, client)
	ginServer := ioc.InitGinServer(logger, handler, db, cache, authHandler, proxyHandler)
	return ginServer
}
